services:
  database:
    image: postgres:latest
    container_name: database_PackandTrack
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./DataBase/squema.sql:/docker-entrypoint-initdb.d/01_squema.sql
      - ./DataBase/script.sql:/docker-entrypoint-initdb.d/02_script.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend_PackandTrack
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy      
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"  

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: frontend_PackandTrack
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: unless-stopped
    depends_on:
      - backend      